name: Annotation
on:
  push:
    paths: ['.github/workflows/annotation.yml']
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error" # Errorレベルのアノテーション
      - run: echo "::warning::This is an warning" # Warningレベルのアノテーション
      - run: echo "::notice::This is an notice" # Noticeレベルのアノテーション

