name: Log group
on:
  push:
    paths: ['.github/workflows/log-group.yml']
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Show environment variables" # ロググループ化の開始
          printenv
          echo "::endgroup::" # ロググループ化の終了

