name: Parallel jobs
on:
  push:
    paths: ['.github/workflows/parallel-jobs.yml']
jobs: # jobsキーへ複数ジョブを定義すれば、並列に実行される
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Third job"

