name: Sequential jobs
on:
  push:
    paths: ['.github/workflows/sequential-jobs.yml']
jobs:
  first: # 依存ジョブが無いため、最初に実行される
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:
    runs-on: ubuntu-latest
    needs: [first] # needsキーへ、依存するfirstジョブのジョブIDを指定
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    needs: [second] # needsキーへ、依存するsecondジョブのジョブIDを指定
    steps:
      - run: sleep 10 && echo "Third job"

